[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pipspack"
version = "0.1.0"

[project.scripts]
spack = "pipspack.runner:main"

[tool.setuptools]
packages = ["pipspack", "spack"]
include-package-data = true

[tool.setuptools.package-data]
pipspack = ["spack/**"]
